### ISSUE TITLE
Incompatibility with new icon naming scheme (IntelliJ NewUI)

### ISSUE THREAD

**Issue by bk-tfo** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons#1]
_REF: [#98 in `extra-icons-plugin`](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/issues/98)_

Incompatibility with new icon naming scheme/new icons as part of the new IntelliJ UI. Creating here as requested.

Plugin version `1.20.0.201`

Stack trace:

 ```
Calling `ClassLoader#getResource` with leading slash doesn't work; strip

com.intellij.diagnostic.PluginException: /extratci/icons/original/community/platform/icons/src/toolwindows/toolWindowStructure.svg [Plugin: lermitage.intellij.extratci]
	at com.intellij.ide.plugins.cl.PluginClassLoader.doFindResource(PluginClassLoader.java:528)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:436)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
	at com.intellij.ui.RasterizedImageDataLoader.getURL(RasterizedImageDataLoader.kt:75)
	at com.intellij.openapi.util.IconLoader.loadCustomVersion(IconLoader.java:89)
	at com.intellij.util.IconUtil.scaleOrLoadCustomVersion(IconUtil.java:670)
	at com.intellij.openapi.wm.impl.ToolWindowIcon.scale(ToolWindowIcon.java:61)
	at com.intellij.openapi.util.IconLoader.loadCustomVersionOrScale(IconLoader.java:117)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.scaleIcon(SquareStripeButton.kt:119)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.access$scaleIcon(SquareStripeButton.kt:1)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.isSelected(SquareStripeButton.kt:156)
	at com.intellij.ui.ToggleActionButton.updateButton(ToggleActionButton.java:50)
	at com.intellij.ui.AnActionButton.update(AnActionButton.java:112)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:293)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:136)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:155)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lastUpdateAndCheckDumb(ActionUtil.java:221)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:468)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by jonathanlermitage** [comment]
Fixed in [1.20.1 release](https://plugins.jetbrains.com/plugin/16604-extra-toolwindow-colorful-icons/versions/stable/181983). For now, published for IDE 2022.2+ EAP (222.2889.14+) only.
